language: objective-c
osx_image: xcode7.3
script:
  - brew update
  - brew install xctool  
  - xctool -project Bamboo.xcodeproj -scheme Bamboo -sdk iphonesimulator clean build test ONLY_ACTIVE_ARCH=NO
