language: objective-c
osx_image: xcode7.3
env: CODE_SIGNING_REQUIRED=NO
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - open -b com.apple.iphonesimulator
  - xcodebuild clean test -project Bamboo.xcodeproj -scheme Bamboo -sdk iphonesimulator9.3 | xcpretty
